// AeneasSoft Monthly Report PDF Generator
import PDFDocument from 'pdfkit';
import { createHash, createSign, generateKeyPairSync } from 'crypto';

function getSigningKey() {
  if (process.env.SIGNING_PRIVATE_KEY && process.env.SIGNING_PUBLIC_KEY) {
    return {
      privateKey: process.env.SIGNING_PRIVATE_KEY,
      publicKey: process.env.SIGNING_PUBLIC_KEY,
      fingerprint: createHash('sha256').update(process.env.SIGNING_PUBLIC_KEY).digest('hex').substring(0, 16),
    };
  }
  const { privateKey, publicKey } = generateKeyPairSync('rsa', {
    modulusLength: 2048,
    publicKeyEncoding: { type: 'spki', format: 'pem' },
    privateKeyEncoding: { type: 'pkcs8', format: 'pem' },
  });
  return { privateKey, publicKey, fingerprint: createHash('sha256').update(publicKey).digest('hex').substring(0, 16) };
}

export async function generateMonthlyReport(
  period: string,
  data: any,
  orgId: string
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const chunks: Buffer[] = [];

      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const { summary, by_agent, by_model, top_errors, traces } = data;
      const { privateKey, fingerprint } = getSigningKey();
      const contentHash = createHash('sha256').update(JSON.stringify(data)).digest('hex');
      const sign = createSign('RSA-SHA256');
      sign.update(JSON.stringify(data));
      const signature = sign.sign(privateKey, 'hex');

      // === PAGE 1: Executive Summary ===
      doc.fontSize(22).font('Helvetica-Bold').text('AeneasSoft Monthly Report', { align: 'center' });
      doc.moveDown(0.3);
      doc.fontSize(14).font('Helvetica').text(`Period: ${period}`, { align: 'center' });
      doc.fontSize(9).fillColor('#888888').text(`Organization: ${orgId}`, { align: 'center' });
      doc.fillColor('#000000');
      doc.moveDown(2);

      doc.fontSize(16).font('Helvetica-Bold').text('Executive Summary');
      doc.moveDown(0.5);

      const s = summary || {};
      const metrics = [
        ['Total Traces', String(s.total_traces || 0)],
        ['Total Cost', `$${(s.total_cost_usd || 0).toFixed(2)}`],
        ['Error Rate', `${((s.error_rate || 0) * 100).toFixed(1)}%`],
        ['Avg Latency', `${(s.avg_latency_ms || 0).toFixed(0)}ms`],
        ['Total Tokens', String(s.total_tokens || 0)],
      ];

      doc.fontSize(11).font('Helvetica');
      for (const [label, value] of metrics) {
        doc.text(`${label}: ${value}`);
      }

      doc.moveDown(2);
      doc.fontSize(9).fillColor('#888888');
      doc.text('Generated by AeneasSoft — https://aeneassoft.com', { align: 'center' });
      doc.fillColor('#000000');

      // === PAGE 2: Top Agents ===
      doc.addPage();
      doc.fontSize(16).font('Helvetica-Bold').text('Top Agents by Cost');
      doc.moveDown(1);

      if (by_agent && by_agent.length > 0) {
        const tblY = doc.y;
        doc.fontSize(9).font('Helvetica-Bold');
        doc.text('Agent', 50, tblY, { width: 150 });
        doc.text('Traces', 200, tblY, { width: 60 });
        doc.text('Cost', 260, tblY, { width: 80 });
        doc.text('Error Rate', 340, tblY, { width: 80 });

        doc.moveTo(50, tblY + 14).lineTo(440, tblY + 14).stroke();
        let y = tblY + 18;
        doc.font('Helvetica');
        for (const agent of by_agent.slice(0, 15)) {
          doc.text(agent.agent_name || agent.agent_id, 50, y, { width: 150 });
          doc.text(String(agent.trace_count), 200, y, { width: 60 });
          doc.text(`$${(agent.total_cost_usd || 0).toFixed(4)}`, 260, y, { width: 80 });
          doc.text(`${((agent.error_rate || 0) * 100).toFixed(1)}%`, 340, y, { width: 80 });
          y += 14;
          if (y > 750) { doc.addPage(); y = 50; }
        }
      } else {
        doc.fontSize(10).font('Helvetica').text('No agent data for this period.');
      }

      // === PAGE 3: Top Models ===
      doc.addPage();
      doc.fontSize(16).font('Helvetica-Bold').text('Top Models by Cost');
      doc.moveDown(1);

      if (by_model && by_model.length > 0) {
        const tblY = doc.y;
        doc.fontSize(9).font('Helvetica-Bold');
        doc.text('Model', 50, tblY, { width: 150 });
        doc.text('Traces', 200, tblY, { width: 60 });
        doc.text('Tokens', 260, tblY, { width: 80 });
        doc.text('Cost', 340, tblY, { width: 80 });

        doc.moveTo(50, tblY + 14).lineTo(440, tblY + 14).stroke();
        let y = tblY + 18;
        doc.font('Helvetica');
        for (const model of by_model.slice(0, 15)) {
          doc.text(model.model || 'unknown', 50, y, { width: 150 });
          doc.text(String(model.trace_count), 200, y, { width: 60 });
          doc.text(String(model.total_tokens), 260, y, { width: 80 });
          doc.text(`$${(model.total_cost_usd || 0).toFixed(4)}`, 340, y, { width: 80 });
          y += 14;
          if (y > 750) { doc.addPage(); y = 50; }
        }
      } else {
        doc.fontSize(10).font('Helvetica').text('No model data for this period.');
      }

      // === PAGE 4: Top Errors ===
      doc.addPage();
      doc.fontSize(16).font('Helvetica-Bold').text('Most Frequent Errors');
      doc.moveDown(1);

      if (top_errors && top_errors.length > 0) {
        doc.fontSize(10).font('Helvetica');
        for (const err of top_errors) {
          doc.font('Helvetica-Bold').text(`${err.error_type} (${err.count}x)`);
          doc.font('Helvetica').text(`  Last seen: ${err.last_seen || 'N/A'}`);
          doc.moveDown(0.3);
        }
      } else {
        doc.fontSize(10).font('Helvetica').text('No errors recorded this period.');
      }

      // === PAGE 5: Trace List ===
      doc.addPage();
      doc.fontSize(16).font('Helvetica-Bold').text('All Traces');
      doc.moveDown(0.5);

      if (traces && traces.length > 0) {
        doc.fontSize(8).font('Helvetica');
        for (const t of traces.slice(0, 100)) {
          if (doc.y > 750) doc.addPage();
          doc.text(`${t.created_at}  ${t.trace_id?.substring(0, 12)}  ${t.name || '-'}  ${t.status}  $${(t.cost_usd || 0).toFixed(4)}  ${t.latency_ms || 0}ms`);
        }
        if (traces.length > 100) {
          doc.moveDown(0.5);
          doc.text(`... and ${traces.length - 100} more traces (download CSV for complete list)`);
        }
      } else {
        doc.fontSize(10).text('No traces for this period.');
      }

      // === PAGE 6: Cryptographic Verification ===
      doc.addPage();
      doc.fontSize(14).font('Helvetica-Bold').text('Cryptographic Integrity Verification');
      doc.moveDown(1);
      doc.fontSize(10).font('Helvetica');
      doc.text('This report is cryptographically signed using RSA-SHA256 (2048-bit).');
      doc.moveDown(1);

      doc.text('SHA-256 Hash:');
      doc.font('Courier').fontSize(7).text(contentHash);
      doc.moveDown(0.5);

      doc.font('Helvetica').fontSize(10).text('RSA-SHA256 Signature:');
      doc.font('Courier').fontSize(6).text(signature.substring(0, 200) + '...');
      doc.moveDown(0.5);

      doc.font('Helvetica').fontSize(10).text(`Key Fingerprint: ${fingerprint}`);
      doc.moveDown(2);

      doc.fontSize(8).fillColor('#888888');
      doc.text('This report was automatically generated by AeneasSoft. It does not constitute legal advice.', { align: 'center' });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}
