interface ScoreInput {
  score: number;
  level: string;
  details?: Record<string, number>;
  checks?: Array<{ name: string; earned: number; weight: number; status: string }>;
}

interface PdfInput {
  traceId: string;
  traceName: string;
  score: ScoreInput;
}

/**
 * Generates a real PDF file (valid binary) from compliance data.
 * Uses raw PDF spec — no external library needed on client.
 */
export function generateCompliancePDF({
  traceId,
  traceName,
  score,
}: PdfInput): Blob {
  const date = new Date().toISOString().split("T")[0];
  const time = new Date().toISOString().split("T")[1].slice(0, 8);

  const details: Record<string, number> = score.details ??
    (score.checks
      ? Object.fromEntries(score.checks.map((c) => [c.name.toLowerCase().replace(/[- ]/g, "_"), c.weight ? Math.round((c.earned / c.weight) * 100) : 0]))
      : {});

  const d = (key: string) => details[key] ?? score.score ?? 0;

  const checklist = [
    { article: "Art. 12(1)", requirement: "Automatic logging of events", pass: d("logging") >= 60 || d("record_keeping") >= 60 },
    { article: "Art. 12(2)", requirement: "Traceability of AI decisions", pass: d("traceability") >= 60 || d("transparency") >= 60 },
    { article: "Art. 12(3)", requirement: "Audit trail retention", pass: d("data_retention") >= 60 || d("audit_trail") >= 60 },
    { article: "Art. 12(4)", requirement: "Logging granularity for monitoring", pass: d("auditability") >= 60 || d("record_keeping") >= 60 },
    { article: "Art. 13(1)", requirement: "Human oversight design", pass: d("human_oversight") >= 60 },
    { article: "Art. 13(2)", requirement: "User information provided", pass: score.score >= 50 },
    { article: "Art. 13(3)", requirement: "Output interpretability", pass: d("traceability") >= 70 || d("transparency") >= 70 },
    { article: "Art. 14(1)", requirement: "Human-in-the-loop mechanisms", pass: d("human_oversight") >= 50 },
  ];

  const passed = checklist.filter((c) => c.pass).length;
  const total = checklist.length;

  // Build text lines for the PDF content stream
  const textLines: string[] = [];
  let y = 750;

  function addLine(text: string, fontSize = 10, bold = false) {
    const font = bold ? "/F2" : "/F1";
    textLines.push(`BT ${font} ${fontSize} Tf ${50} ${y} Td (${escapePdf(text)}) Tj ET`);
    y -= fontSize + 4;
  }

  function addGap(px = 10) { y -= px; }

  addLine("AENEASSOFT EU AI ACT ARTICLE 12 REPORT", 16, true);
  addGap(8);
  addLine(`Trace ID: ${traceId}`, 9);
  addLine(`Trace Name: ${traceName}`, 9);
  addLine(`Generated: ${date} at ${time} UTC`, 9);
  addLine(`Overall Score: ${score.score}/100 (${score.level})`, 10, true);
  addLine(`Checks Passed: ${passed}/${total}`, 9);
  addGap(12);

  addLine("ARTICLE 12 CHECKLIST", 12, true);
  addGap(4);
  for (const item of checklist) {
    const status = item.pass ? "PASS" : "FAIL";
    addLine(`[${status}]  ${item.article} - ${item.requirement}`, 9);
  }

  addGap(12);
  addLine("DETAILED METRICS", 12, true);
  addGap(4);
  for (const [key, val] of Object.entries(details)) {
    const label = key.replace(/_/g, " ");
    addLine(`${label}: ${val}%`, 9);
  }

  addGap(16);
  addLine("DISCLAIMER", 11, true);
  addGap(4);
  addLine("This report was automatically generated by AeneasSoft.", 8);
  addLine("It provides an indicative assessment based on observed agent", 8);
  addLine("behavior and should not be considered legal advice.", 8);
  addLine("Consult qualified legal counsel for formal certification.", 8);
  addGap(8);
  addLine("Report generated by AeneasSoft v1.0 - https://aeneassoft.com", 8);

  // Build a minimal valid PDF
  const stream = textLines.join("\n");
  const streamLength = new TextEncoder().encode(stream).length;

  const objects: string[] = [];
  let offsets: number[] = [];

  // Object 1: Catalog
  objects.push("1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj");
  // Object 2: Pages
  objects.push("2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj");
  // Object 3: Page
  objects.push(
    "3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842]\n" +
    "   /Contents 4 0 R /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> >>\nendobj"
  );
  // Object 4: Content stream
  objects.push(
    `4 0 obj\n<< /Length ${streamLength} >>\nstream\n${stream}\nendstream\nendobj`
  );
  // Object 5: Font (Helvetica)
  objects.push(
    "5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj"
  );
  // Object 6: Font (Helvetica-Bold)
  objects.push(
    "6 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>\nendobj"
  );

  // Assemble PDF
  let pdf = "%PDF-1.4\n";
  offsets = [];
  for (const obj of objects) {
    offsets.push(pdf.length);
    pdf += obj + "\n";
  }

  const xrefOffset = pdf.length;
  pdf += "xref\n";
  pdf += `0 ${objects.length + 1}\n`;
  pdf += "0000000000 65535 f \n";
  for (const off of offsets) {
    pdf += off.toString().padStart(10, "0") + " 00000 n \n";
  }
  pdf += "trailer\n";
  pdf += `<< /Size ${objects.length + 1} /Root 1 0 R >>\n`;
  pdf += "startxref\n";
  pdf += `${xrefOffset}\n`;
  pdf += "%%EOF\n";

  return new Blob([pdf], { type: "application/pdf" });
}

function escapePdf(text: string): string {
  return text
    .replace(/\\/g, "\\\\")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)")
    .replace(/[^\x20-\x7E]/g, "?");  // Strip non-ASCII for PDF safety
}
